apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb
  labels:
    app: catalogdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogdb
  template:
    metadata:
      labels:
        app: catalogdb
    spec:
      containers:
      - name: catalogdb
        image: mcr.microsoft.com/mssql/server:latest
        ports:
        - containerPort: 1433
          name: mssqlserver
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "ProductApi(!)"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogdb
spec:
  ports:
  - port: 1433
  selector:
    app: catalogdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi
  labels:
    app: catalogapi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  selector:
    matchLabels:
      app: catalogapi
  template:
    metadata:
      labels:
        app: catalogapi
    spec:
      containers:
      - name: catalogapi
        image: jewelsacr.azurecr.io/jewelscatalogapi:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: DatabaseServer
          value: "mssqlserver"
        - name: DatabaseName
          value: "CatalogDb"
        - name: DatabaseUser
          value: "sa"
        - name: DatabasePassword
          value: "ProductApi(!)"
        - name: Externalbaseurl
          value: "http://localhost:80"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: catalogapi